#!/usr/bin/env python

# Copyright (c) 2015 Raytheon BBN Technologies Corp.  All rights reserved.

from __future__ import absolute_import

from fasguard_benign_traffic_collection import main
import sys

sys.exit(main(sys.argv))
